### ISSUE TITLE
Observed fan at 100% when not calibrating at low GPU temperature

### ISSUE THREAD

**Issue by gordan-bobic** [m4rkw/fanotaur#3]
Observed earlier fanotaur setting fan speed to 100% without an active calibration run and at low GPU temperature (60C).

Will need to monitor for a reproducer.

**Comment by gordan-bobic** [comment]
Very reproducible, comes up on the Hetzner machines all the time. Reboot, look at gs, it's at 100% at 60C.

**Comment by m4rkw** [comment]
please update to v0.4 and enable debug mode in the config file:

````
debug: true
````

reproduce the issue and paste the logs

**Comment by m4rkw** [comment]
is this still happening?

**Comment by gordan-bobic** [comment]
I believe @biesbjerg reported a similar issue earlier today. It may be the same or related.

**Comment by m4rkw** [comment]
so is it still happening for you?

**Comment by gordan-bobic** [comment]
I haven't noticed it recently but I only use it on the Hetzner machines which are over 75C all the time and this at 100% anyway.
